name: Chrono Cross (USA)
sha1: 26c3da2599af76f7e352b8594d048b527d6bd0d9
options:
  basename: slps_023.64
  target_path: disc/extracted/prog/slps_023.64
  elf_path: build/slps_023.64.elf
  base_path: ../
  platform: psx
  compiler: PSYQ

  asm_path: asm/slps_023.64
  src_path: src/slps_023.64
  build_path: build
  # create_asm_dependencies: True

  ld_script_path: linker/slps_023.64.ld
  ld_dependencies: True

  find_file_boundaries: False
  gp_value: 0x0
  global_vram_start: 0x80010000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".sdata", ".data", ".sbss", ".bss"]
  # auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path: 
    - config/symbol_addrs.slps_023.64.txt
  reloc_addrs_path: 
    - config/reloc_addrs.txt

  undefined_funcs_auto_path: linker/undefined_funcs_auto.slps_023.64.txt
  undefined_syms_auto_path: linker/undefined_syms_auto.slps_023.64.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  migrate_rodata_to_functions: false
  data_string_guesser_level: 2

  ld_bss_is_noload: True
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    bss_size: 0x40000 # yolo
    bss_contains_common: True
    align: 4
    subsegments:
      - [0x800, asm]
      - [0x18F20, asm, psyq/libspu]
      - [0x19DF0, asm]
      - [0x1A2BC]
      - [0x1A670, asm]
      - [0x46C6C, data] # 8005646C START RODATA
      - [0x46EF0]
      - [0x46EFC, data] # 800566FC
      - [0x5983A, data] # 8006903A
      - [0x59DF4, data] # 800695F4
      - [0x5A834, data] # 8006A034
      - [0x5ACD4]
      - [0x5ACD8, data]
      - [0x5B1F5, data] # actually SDATA
      - [0x5C8BC, data] # 8006C0BC # END RODATA
      - [0x5C93C, data] # 8006C13C
      - [0x63AC0, data] # 800732C0
      - [0x858B0, data] # 800950B0
      - [0x85FE4, asm] # 800957E4
      - [0x98248, data] # 800A7A48
      - [0x9A800]
